- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - include: tasks/dotfile.yml
    - include: tasks/ssh.yml
    - include: tasks/core-setup.yml
    - include: tasks/git-setup.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/p10k-setup.yml
    #- include: tasks/nvim-setup.yml
    #- include: tasks/nvchad-setup.yml


    

