- hosts: localhost
  vars:
    personal_source_key: "./.ssh/id_ed25519_personal"
    personal_dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519_personal"
    work_source_key: "./.ssh/id_ed25519_work"
    work_dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519_work"
    personal: "{{ lookup('env', 'HOME') }}/personal"
    work: "{{ lookup('env', 'HOME') }}/work"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - personal
        - work
        - nvim

  tasks:
    - name: Setup SSH
      import_tasks: tasks/ssh.yaml
      tags:
        - ssh

    - name: Core Setup
      import_tasks: tasks/core-setup.yaml
      tags:
        - core

    - name: Setup NVim and NVChad
      import_tasks: tasks/nvim-setup.yaml
      tags:
        - nvim

    - name: Setup Personal Projects
      import_tasks: tasks/personal-projects.yaml
    - name: Setup ZSH
      import_tasks: tasks/zsh-setup.yaml
      tags: 
        - zsh
    - name: Dotfiles
      import_tasks: tasks/dotfile.yaml
      tags:
        - dotfiles
    - name: Setup Fonts
      import_tasks: tasks/fonts-setup.yaml
      tags:
        - fonts
        
      tags:
        - personal-projects

    - name: Setup Work Projects
      import_tasks: tasks/work-setup.yaml
      tags:
        - work-projects
