- hosts: localhost
  vars:
    personal_source_key: "./.ssh/id_ed25519_personal"
    personal_dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519_personal"
    work_source_key: "./.ssh/id_ed25519_work" 
    work_dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519_work"
    personal: "{{ lookup('env', 'HOME') }}/personal"
    work: "{{ lookup('env', 'HOME') }}/work"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - personal
        - work
        - nvim

  tasks:

    - import_tasks: tasks/dotfile.yaml
      tags:
        - dotfile
        - personal
    

    - import_tasks: tasks/ssh.yaml 
      tags:
        - ssh
        - personal


    - import_tasks: tasks/core-setup.yaml
      tags:
        - core
        - personal

    

    - import_tasks: tasks/zsh-setup.yaml
      tags:
        - zsh
        - personal
    

    - import_tasks: tasks/p10k-setup.yaml
      tags:
        - p10k

    - import_tasks: tasks/nvim-setup.yaml
      tags:
        - nvim
        - personal
      
        
    - import_tasks: tasks/nvchad-setup.yaml
      tags:
        - nvchad
        - personal
  

    - import_tasks: tasks/fonts-setup.yaml
      tags:
        - fonts
        - personal

    - import_tasks: tasks/personal-projects.yaml
      tags:

        - personal-projects
 
        
    - import_tasks: tasks/work-setup.yaml
      tags:
        - work-projects
        
    - import_tasks: tasks/chrome-vscode-setup.yaml
      tags:
        - chrome-vscode
        
    
      

    

