- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (lua, libtool, libtool-bin, gettext,unzip)
  become: true
  apt:
    name: ["lua5.1", "libtool", "libtool-bin", "gettext","unzip","curl"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 (htop lsof ccache ninja-build python3-pip moreutils ripgrep)
  become: true
  apt:
    name: ["htop", "lsof", "ccache", "ninja-build", "python3-pip", "moreutils","ripgrep","fzf","cargo","fd-find"]
  tags:
    - install
    - core
    - neovim


#- name: Install Node.js and npm
#  become: true
#  block:
#    - name: Add NodeSource distributions for Node.js 16
#      shell: "curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -"
#    - name: Install Node.js and npm
#      apt:
#        name: ["nodejs"]
#        state: present
#  tags:
#    - install
#    - core


- name: Install Python3 and venv for virtual environment creation
  become: true
  
  apt:
    name: ["python3", "python3-venv"]
    state: present
  tags:
    - install
    - core


