- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become: yes
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (lua, libtool, libtool-bin, gettext,unzip)
  become: yes
  apt:
    name: ["lua5.1", "libtool", "libtool-bin", "gettext","unzip"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 (htop lsof ccache ninja-build python3-pip moreutils ripgrep)
  become: yes
  apt:
    name: ["htop", "lsof", "ccache", "ninja-build", "python3-pip", "moreutils","ripgrep"]
  tags:
    - install
    - core
    - neovim

- name: Install Node.js and npm
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: present
  tags:
    - install
    - core

- name: Install Python3 and venv for virtual environment creation
  become: yes
  apt:
    name: ["python3", "python3-venv"]
    state: present
  tags:
    - install
    - core



