- name: Remove neovim
  shell: rm -rf ~/neovim
  tags:
    - install
    - neovim

- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim" # Specify the stable branch or a specific release tag
  tags:
    - install
    - neovim 


- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo -j 20"
  tags:
    - install
    - neovim


- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags:
    - install
    - neovim

- name: Install NvChad
  become: true
  become_user: kdlocpanda
  git:
    repo: 'https://github.com/NvChad/NvChad.git'
    dest: '~/.config/nvim'
    clone: yes
    update: yes
    depth: 1

- name: Clone GitHub Copilot Plugin Repository
  become: true
  become_user: kdlocpanda
  git:
    repo: 'https://github.com/github/copilot.vim.git'
    dest: '~/.vim/pack/github/start/copilot.vim'
    clone: yes

- name: Install LunarVim
  become: true
  become_user: kdlocpanda
