- name: Update and upgrade apt packages
  become: yes
  apt:
    update_cache: yes
    upgrade: 'dist'
    autoremove: yes
    autoclean: yes

- name: Clone Powerlevel10k for Oh My Zsh
  git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
    clone: yes
    update: yes
    depth: 1

- name: Set Powerlevel10k as the Zsh theme in .zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    regexp: '^ZSH_THEME=.*'
    line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'
    create: yes
  become: yes
  become_user: kdlocpanda




- name: Install fonts-powerline
  become: yes
  apt:
    name: fonts-powerline
    state: present

