- name: Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes
    upgrade: 'dist'
    autoremove: yes
    autoclean: yes

- name: Clone Powerlevel10k for Oh My Zsh
  git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: "/home/cnoel/.oh-my-zsh/custom/themes/powerlevel10k"
    clone: yes
    update: yes
    depth: 1
  become: true
  become_user: cnoel

- name: Set Powerlevel10k as the Zsh theme in .zshrc
  lineinfile:
    path: "/home/cnoel/.zshrc"
    regexp: '^ZSH_THEME=.*'
    line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'
    create: yes
  become: true
  become_user: cnoel
