- name: Update and upgrade apt packages
  become: yes
  apt:
    update_cache: yes
    upgrade: 'dist'
    autoremove: yes
    autoclean: yes

- name: Install Powerlevel10k
  git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: '~/powerlevel10k'
    clone: yes
    update: yes
    depth: 1

- name: Add Powerlevel10k to zshrc
  lineinfile:
    path: /home/kdlocpanda/.zshrc
    regexp: '^ZSH_THEME=.*'
    line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'
    create: yes
  become: yes
  become_user: kdlocpanda



- name: Install fonts-powerline
  become: yes
  apt:
    name: fonts-powerline
    state: present

