- name: Personal my_repos Exists!
  stat:
    path: "{{ personal }}/my_repos"
  register: my_repos
  
- name: Start ssh-agent
  become: true
  shell: eval "$(ssh-agent -s)"
  tags:
    - ssh

- name: Setup SSH config
  copy:
    dest: "{{ lookup('env', 'HOME') }}/.ssh/config"
    content: |
      Host personal.github.com
        HostName github.com
        User git
        IdentityFile {{ personal_dest_key }}

      Host work.github.com
        HostName github.com
        User git
        IdentityFile {{ work_dest_key }}
  tags:
    - ssh

- name: Personal Project - template_streamlit
  ansible.builtin.git:
    repo: 'https://github.com/joshyorko/template_streamlit.git'
    dest: "{{ personal }}/template_streamlit"
  tags:
    - template_streamlit



- name: Personal Project - forgpt
  ansible.builtin.git:
    repo: 'https://github.com/joshyorko/forgpt.git'
    dest: "{{ personal }}/forgpt"
  tags:
    - forgpt

- name: Personal Project - ansible
  ansible.builtin.git:
    repo: 'https://github.com/joshyorko/ansible.git'
    dest: "{{ personal }}/ansible"
  tags:
    - ansible



- name: Personal Project - openai_plugins
  ansible.builtin.git:
    repo: 'https://github.com/joshyorko/openai_plugins.git'
    dest: "{{ personal }}/openai_plugins"
  tags:
    - openai_plugins

- name: Personal Project - docusense
  ansible.builtin.git:
    repo: 'https://github.com/joshyorko/docusense.git'
    dest: "{{ personal }}/docusense"
  tags:
    - docusense

- name: Personal Project - docusense_2.0
  ansible.builtin.git:
    repo: 'https://github.com/joshyorko/docusense_2.0.git'
    dest: "{{ personal }}/docusense_2.0"
  tags:
    - docusense_2.0


- name: Personal Project - Mini-IronRipper
  ansible.builtin.git:
    repo: 'https://github.com/joshyorko/Mini-IronRipper.git'
    dest: "{{ personal }}/Mini-IronRipper"
  tags:
    - Mini-IronRipper



- name: Personal Project - yorko-resume
  ansible.builtin.git:
    repo: 'https://github.com/joshyorko/yorko-resume.git'
    dest: "{{ personal }}/yorko-resume"
  tags:
    - yorko-resume


- name: Personal Project - company_datalake 
  ansible.builtin.git:
    repo: 'https://github.com/joshyorko/company_datalake.git'
    dest: "{{ personal }}/company_datalake"
  tags: 
    - company_datalake

- name: Personal Project - socialscrape_web_app
  become_user: kdlocpanda
  ansible.builtin.git:
    repo: 'git@github.com:joshyorko/socialscrape_web_app.git'
    dest: "{{ personal }}/socialscrape_web_app"
  tags: 
    - socialscrape_web_app

- name: Personal Project - networkLogsscrape
  ansible.builtin.git:
    repo: 'git@github.com:joshyorko/networkLogsscrape.git'
    dest: "{{ personal }}/networkLogsscrape"
  tags:     
    - networkLogsscrape-ssh