- name: my_repos exists
  stat:
    path: "{{ personal }}/my_repos"
  register: my_repos

- name: Personal Project - template_streamlit
  ansible.builtin.git:
    repo: 'https://github.com/joshyorko/template_streamlit.git'
    dest: "{{ personal }}/template_streamlit"
  tags:
    - template_streamlit



- name: Personal Project - forgpt
  ansible.builtin.git:
    repo: 'https://github.com/joshyorko/forgpt.git'
    dest: "{{ personal }}/forgpt"
  tags:
    - forgpt

- name: Personal Project - ansible
  ansible.builtin.git:
    repo: 'https://github.com/joshyorko/ansible.git'
    dest: "{{ personal }}/ansible"
  tags:
    - ansible

- name: Personal Project - work
  ansible.builtin.git:
    repo: 'https://github.com/joshyorko/work.git'
    dest: "{{ personal }}/work"
  tags:
    - work

- name: Personal Project - openai_plugins
  ansible.builtin.git:
    repo: 'https://github.com/joshyorko/openai_plugins.git'
    dest: "{{ personal }}/openai_plugins"
  tags:
    - openai_plugins

- name: Personal Project - docusense
  ansible.builtin.git:
    repo: 'https://github.com/joshyorko/docusense.git'
    dest: "{{ personal }}/docusense"
  tags:
    - docusense

- name: Personal Project - docusense_2.0
  ansible.builtin.git:
    repo: 'https://github.com/joshyorko/docusense_2.0.git'
    dest: "{{ personal }}/docusense_2.0"
  tags:
    - docusense_2.0


- name: Personal Project - Mini-IronRipper
  ansible.builtin.git:
    repo: 'https://github.com/joshyorko/Mini-IronRipper.git'
    dest: "{{ personal }}/Mini-IronRipper"
  tags:
    - Mini-IronRipper



- name: Personal Project - yorko-resume
  ansible.builtin.git:
    repo: 'https://github.com/joshyorko/yorko-resume.git'
    dest: "{{ personal }}/yorko-resume"
  tags:
    - yorko-resume


