- name: Personal my_repos Exists!
  stat:
    path: "{{ personal }}/my_repos"
  register: my_repos
  tags:
    - personal-projects
    - repo-exists

- name: Personal Project - template_streamlit
  ansible.builtin.git:
    repo: 'https://github.com/joshyorko/template_streamlit.git'
    dest: "{{ personal }}/my_repos/template_streamlit"
  tags:
    - template_streamlit
    - personal-projects

- name: Personal Project - forgpt
  ansible.builtin.git:
    repo: 'https://github.com/joshyorko/forgpt.git'
    dest: "{{ personal }}/my_repos/forgpt"
  tags:
    - forgpt
    - personal-projects

- name: Personal Project - ansible
  ansible.builtin.git:
    repo: 'https://github.com/joshyorko/ansible.git'
    dest: "{{ personal }}/my_repos/ansible"
  tags:
    - ansible
    - personal-projects

- name: Personal Project - openai_plugins
  ansible.builtin.git:
    repo: 'https://github.com/joshyorko/openai_plugins.git'
    dest: "{{ personal }}/my_repos/openai_plugins"
  tags:
    - openai_plugins
    - personal-projects

- name: Personal Project - docusense
  ansible.builtin.git:
    repo: 'https://github.com/joshyorko/docusense.git'
    dest: "{{ personal }}/my_repos/docusense"
  tags:
    - docusense
    - personal-projects

- name: Personal Project - docusense_2.0
  ansible.builtin.git:
    repo: 'https://github.com/joshyorko/docusense_2.0.git'
    dest: "{{ personal }}/my_repos/docusense_2.0"
  tags:
    - docusense_2.0
    - personal-projects

- name: Personal Project - Mini-IronRipper
  ansible.builtin.git:
    repo: 'https://github.com/joshyorko/Mini-IronRipper.git'
    dest: "{{ personal }}/my_repos/Mini-IronRipper"
  tags:
    - Mini-IronRipper
    - personal-projects

- name: Personal Project - yorko-resume
  ansible.builtin.git:
    repo: 'https://github.com/joshyorko/yorko-resume.git'
    dest: "{{ personal }}/my_repos/yorko-resume"
  tags:
    - yorko-resume
    - personal-projects

- name: Personal Project - company_datalake 
  ansible.builtin.git:
    repo: 'https://github.com/joshyorko/company_datalake.git'
    dest: "{{ personal }}/my_repos/company_datalake"
  tags: 
    - company_datalake
    - personal-projects

- name: Personal Project - socialscrape_web_app
  become_user: kdlocpanda
  ansible.builtin.git:
    repo: 'git@github.com:joshyorko/socialscrape_web_app.git'
    dest: "{{ personal }}/my_repos/socialscrape_web_app"
    accept_hostkey: yes
  tags: 
    - socialscrape_web_app
    - personal-projects

- name: Personal Project - networkLogsscrape
  ansible.builtin.git:
    repo: 'git@github.com:joshyorko/networkLogsscrape.git'
    dest: "{{ personal }}/my_repos/networkLogsscrape"
    accept_hostkey: yes
  tags:     
    - networkLogsscrape-ssh
    - personal-projects

- name: Personal Project - josh_bot
  ansible.builtin.git:
    repo: 'git@github.com:joshyorko/josh_bot.git'
    dest: "{{ personal }}/my_repos/josh_bot"
    accept_hostkey: yes
  tags:     
    - josh_bot
    - personal-projects
