- name: Update and upgrade apt packages
  become: yes
  apt:
    update_cache: yes
    upgrade: 'dist'
    autoremove: yes
    autoclean: yes

- name: Install Powerlevel10k
  git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: '~/powerlevel10k'
    clone: yes
    update: yes
    depth: 1

- name: Add Powerlevel10k to zshrc
  lineinfile:
    path: /home/kdlocpanda/.zshrc
    regexp: '^ZSH_THEME=.*'
    line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'
    create: yes
  become: yes
  become_user: kdlocpanda



- name: Install fonts-powerline
  become: yes
  apt:
    name: fonts-powerline
    state: present

- name: Install VS Code Insiders
  become: yes
  block:
    - name: Add Microsoft GPG key
      ansible.builtin.apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add VS Code repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/code stable main
        state: present

    - name: Install code-insiders
      apt:
        name: code-insiders
        state: present

- name: Install Google Chrome
  become: yes
  block:
    - name: Download Google Chrome
      get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: /tmp/google-chrome-stable_current_amd64.deb

    - name: Install Google Chrome
      apt:
        deb: /tmp/google-chrome-stable_current_amd64.deb
