- name: Ensure .ssh directory exists
  file:
    dest: "{{ personal_dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh

- name: Change ownership of .ssh directory
  become: true
  file:
    path: "{{ lookup('env', 'HOME') }}/.ssh"
    owner: kdlocpanda
    group: kdlocpanda
    recurse: yes
  tags:
    - dotfiles
    - install
    - ssh

- name: Install  Personal ssh key
  copy:
    src: "{{ personal_source_key }}"
    dest: "{{ personal_dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh
- name: Install Personal ssh key public
  copy:
    src: "{{ personal_source_key }}.pub"
    dest: "{{ personal_dest_key }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh

- name: Install  Work ssh key
  copy:
    src: "{{ work_source_key }}"
    dest: "{{ work_dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ssh key public
  copy:
    src: "{{ work_source_key }}.pub"
    dest: "{{ work_dest_key }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh

