- name: Work Repo Exists!
  stat:
    path: "{{ work }}/repos"
  register: my_repos
  
- name: Work - work
  ansible.builtin.git:
    repo: 'git@github.com:mygainwell/maui-data-integration.git'
    dest: "{{ work }}/repos"
    accept_hostkey: yes
  tags:
    - work

- name: Work - SASI
  ansible.builtin.git:
    repo: 'git@github.com:mygainwell/SASI-Project.git'
    dest: "{{ work }}/repos"
    accept_hostkey: yes
  tags: 
    - work

- name: Work - IronRipper3K
  ansible.builtin.git:
    repo: 'git@github.com:mygainwell/IronRipper3K.git'
    dest: "{{ work }}/repos"
    accept_hostkey: yes
  tags:
    - work


