- name:  work_repos Exists!
  stat:
    path: "{{ work }}/work_repos"
  register: work_repos
  
  
- name: Work - MAUI
  ansible.builtin.git:
    repo: 'git@github.com:mygainwell/maui-data-integration.git'
    dest: "{{ work }}/work_repos/maui-data-integration"
    accept_hostkey: yes
  tags:
    - maui-data-integration

- name: Work - SASI
  ansible.builtin.git:
    repo: 'git@github.com:mygainwell/SASI-Project.git'
    dest: "{{ work }}/work_repos/SASI-Project"
    accept_hostkey: yes
  tags:
    - SASI-Project

- name: Work - IronRipper3K
  ansible.builtin.git:
    repo: 'git@github.com:mygainwell/IronRipper3K.git'
    dest: "{{ work }}/work_repos/IronRipper3K"
    accept_hostkey: yes
  tags:
    - IronRipper3K