- name: Install ZSH
  apt: 
    name: zsh
  become: yes
  tags: &tags_for_zsh_tasks [ m 'zsh' ]

- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  become: yes
  tags: *tags_for_zsh_tasks

- name: Check that the .oh-my-zsh exists
  stat:
    path: /home/kdlocpanda/.oh-my-zsh
  register: oh_my_stats
  tags: *tags_for_zsh_tasks

- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  become: yes
  tags: *tags_for_zsh_tasks
  when: oh_my_stats.stat.exists == False
  become_user: kdlocpanda

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  become: yes
  tags: *tags_for_zsh_tasks

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"
  become: yes
  tags: *tags_for_zsh_tasks

- name: Add Plugins to .zshrc
  lineinfile:
    path: /home/kdlocpanda/.zshrc
    regexp: '^plugins=.*'
    line: 'plugins=(git python zsh-autosuggestions zsh-syntax-highlighting)'
    create: yes
  become: yes
  become_user: kdlocpanda
  tags: *tags_for_zsh_tasks

- name: Define functions for .zshrc
  set_fact:
    zshrc_functions: |
      switch_to_personal() {
        ssh-add -D
        ssh-add ~/.ssh/id_ed25519_personal
        git config --global user.email "joshua.yorko@gmail.com"
        echo "Switched to Personal SSH and Git Config."
      }

      switch_to_work() {
        ssh-add -D
        ssh-add ~/.ssh/id_ed25519_work
        git config --global user.email "joshua.yorko@gainwelltechnologies.com"
        echo "Switched to Work SSH and Git Config."
      }

- name: Add functions to .zshrc
  lineinfile:
    path: /home/kdlocpanda/.zshrc
    line: "{{ zshrc_functions }}"
    create: yes
  become: yes
  become_user: kdlocpanda


- name: Set ZSH as default shell in .bashrc
  lineinfile:
    path: /home/kdlocpanda/.bashrc
    line: 'exec zsh'
    create: yes
  become: yes
  become_user: kdlocpanda
  tags: *tags_for_zsh_tasks

