- name: Installing stow
  become: true
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow


- name: Cloning .dotfiles
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_dest_dir }}/.dotfiles"
    recursive: yes
    update: yes
    force: no
  tags:
    - install
    - dotfiles
    - stow

- name: Stow dotfiles
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell: cd $HOME/.dotfiles
  tags:
    - install
    - dotfiles
    - stow
