# Global Variables for All Hosts

# User and Directories
ansible_user: kdlocpanda
ansible_become: true
ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"

# NVim Setup
nvim_config_repo: "https://github.com/neovim/neovim.git"
nvim_install_dir: "{{ lookup('env', 'HOME') }}/neovim"



# Fonts Setup
fonts_repo: "https://github.com/ryanoasis/nerd-fonts"
fonts_install_dir: "{{ lookup('env', 'HOME') }}/.local/share/fonts"

# Dotfiles
dotfiles_repo: "https://github.com/joshyorko/.dotfiles"
dotfiles_dest_dir: "{{ lookup('env', 'HOME') }}"

# SSH Keys
personal_source_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
personal_dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
personal_source_key_pub: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
personal_dest_key_pub: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"

