- name: Install ZSH
  apt:
    name: zsh
  become: true
  tags: &tags_for_zsh_tasks ['zsh','personal','work']

- name: Change shell to zsh for {{ ansible_user }}
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
  become: true
  tags: *tags_for_zsh_tasks

- name: Check that the .oh-my-zsh exists
  stat:
    path: "/home/{{ ansible_user }}/.oh-my-zsh"
  register: oh_my_stats
  tags: *tags_for_zsh_tasks

- name: Install Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  become: true
  become_user: "{{ ansible_user }}"
  when: oh_my_stats.stat.exists == False
  tags: *tags_for_zsh_tasks

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "/home/{{ ansible_user }}/.oh-my-zsh/plugins/zsh-autosuggestions"
  become: true
  become_user: "{{ ansible_user }}"
  tags: *tags_for_zsh_tasks

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "/home/{{ ansible_user }}/.oh-my-zsh/plugins/zsh-syntax-highlighting"
  become: true
  become_user: "{{ ansible_user }}"
  tags: *tags_for_zsh_tasks

- name: Install zsh-completions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-completions.git'
    dest: "/home/{{ ansible_user }}/.oh-my-zsh/plugins/zsh-completions"
  become: true
  become_user: "{{ ansible_user }}"
  tags: *tags_for_zsh_tasks


